### ISSUE TITLE
Tooltip de estado de materia esta mal

### ISSUE THREAD

**Issue by gonnza** [UTNianos/frontend#21]
![image](https://user-images.githubusercontent.com/352474/28491175-ac4f7a92-6ec2-11e7-8e9b-b846e6f3e103.png)

muestra ese [object, object] ahi

**Comment by fdemian** [comment]
Ok, aparentemente [object, object] es el badge (el circulito de color con el estado). Esto le esta poniendo un parámetro title que tiene serializa el valor como [object Object] y eso es lo que muestra.

**Comment by fdemian** [comment]
Solucionado!

**Comment by Javier-Rotelli** [comment]
Creo que deberiamos tomar como politica solo cerrar cuando este mergeado a master. 
Discuss

**Comment by fdemian** [comment]
Tiene sentido. No tengo sentimientos para un lado ni para otro. De todas formas si vamos a hacer eso necesitamos mínimo una forma de marcar el ticket como "resuelto, pero falta mergear".  También necesitamos una política de hacer cosas en general.
