### ISSUE TITLE
.js o .jsx ?

### ISSUE THREAD

**Issue by gndelia** [UTNianos/frontend#34]
Veo que ambas extensiones se usan indistintamente a lo largo del proyecto.

Ejemplos

> App/LayoutDestktop.js
> App/Home.jsx

Hay algun criterio ? Deberiamos usar _una_ u _otra_ pero mezclarlas no tiene mucho sentido

**Comment by fdemian** [comment]
En teoría .JSX se usa para todo lo que use el pseudohtml de react (codigo JSX). La verdad, a mi no me convence demasiado usar esa extensión y tengo entendido que quedo en desuso. 

Lo estabamos usando como convención para el archivo principal de cada carpeta. Por mi resolvemos la consistencia metiendole .js a todo y deprecamos la extensión .jsx .

**Comment by gndelia** [comment]
Si pero por ejemplo `LayoutDestktop.js` tiene codigo Jsx asique creo que no está siguiendo demasiado esa convencion tampoco 🤷‍♂

**Comment by fdemian** [comment]
Era mi entendimiento que estabamos usando esa convención para los archivos con código JSX que además estaban eran el archivo principal de esa carpeta. Tal vez en algún momento murio eso. 

Por mi usaria .js para todo, ya que te los reconocen todos los editores de texto sin drama (mientras que  para .JSX al menos la última vez que me fije, había que configurar todo y era una paja).

**Comment by Javier-Rotelli** [comment]
Agree. js para todes y lesto. 
si no hay oposicion mañana cierro este ~antro~ ticket

**Comment by fdemian** [comment]
Consenso alcanzado. Cierre.

**Comment by gndelia** [comment]
dale, igual entiendo que el cierre implica hacer el rename de todos los files con un PR 👅
