### ISSUE TITLE
Console errors on index.js file

### ISSUE THREAD

**Issue by gndelia** [UTNianos/frontend#35]
Para ir metiendome de a poco siempre lo mejore es.. arreglar bugs !

Hay 3 pequeños errores en la consola:

> index.js:1446 Warning: Please use `require("history").createBrowserHistory` instead of `require("history/createBrowserHistory")`. Support for the latter will be removed in the next major release.

Simplemente cambiar un método

> Warning: Each child in a list should have a unique "key" prop.

Este es al crear las AppRoutes

> mapDispatchToProps() in Connect(AppRoute) must return a plain object. Instead received undefined.

creo que es bastante self-explanatory 😛

**Comment by fdemian** [comment]
Es para pegarle a estos tipos, no dejan nada estable en dos meses 😄 . 
Le pones vos a esto? Fijate si hay algún package desactualizado y eso es parte del problema.

**Comment by gndelia** [comment]
Agrego este pequeño warning, asi dejamos todo limpio

> Warning: <BrowserRouter> ignores the history prop. To use a custom history, use `import { Router }` instead of `import { BrowserRouter as Router }`.

**Comment by gndelia** [comment]
no hay mas errores - cierro.
