### ISSUE TITLE
Migrar TravisCi de Services a GithubApp

### ISSUE THREAD

**Issue by gndelia** [UTNianos/frontend#37]
Los pull requests están trabados (ej ver #36 )

[Segun este issue](https://github.com/travis-ci/travis-ci/issues/10204) y otros links, GitHub services fue deprecado y hay que instalar travis como GitHub App (igual que CodeCov que ya está en app)

Todo esto, ademas, se le suma que aparentemente travis-ci esta migrando el dominio de travis-ci.org a travis-ci.com 🤷‍♂ 

https://docs.travis-ci.com/user/migrate/open-source-repository-migration

> On May 2nd, 2018 Travis CI announced that open source projects will be joining private projects on travis-ci.com!

desde entonces los PR están clavados

**Comment by gndelia** [comment]
Segun [Este link](https://docs.travis-ci.com/user/migrate/open-source-repository-migration) deberia aparecer un boton de migrate 

![image](https://user-images.githubusercontent.com/352474/57196943-f6711000-6f37-11e9-9a54-92388a75541f.png)


pero en travis-ci.com me dice

![image](https://user-images.githubusercontent.com/352474/57196968-1ef90a00-6f38-11e9-8ff2-2b1ac2ea03bb.png)


Intenté deshabilitar para frontend el proyecto asi no aparece mas como usado en legacy

![image](https://user-images.githubusercontent.com/352474/57196974-30421680-6f38-11e9-99d5-3ddee7361495.png)


pero se ve que hay algo cacheado o hay que esperar por algo.
Que se yo

**Comment by gndelia** [comment]
Segun [esto](https://docs.travis-ci.com/user/migrate/open-source-on-travis-ci-com/#existing-open-source-repositories-on-travis-ciorg) hay que mandar mail a support y ellos migran.

now we wait 

![simpsons waiting](https://thumbs.gfycat.com/LegalPalatableJunebug-size_restricted.gif)

**Comment by fdemian** [comment]
Ufff...colgue bocha con esto, después más a la tarde veo si lo puedo hacer yo, pero idem, no me figuraba nada.
Que bien que no colgaste con esto :P.

**Comment by fdemian** [comment]
Debería estar migrado esto.

**Comment by gndelia** [comment]
Despues lo reviso. 

En ppio el webhook (que yo lo borré creo) aparece apuntando a travis-ci.org y no travis-ci.com asique eso me hace ruido. Estas seguro que eso está bien?

En los settings de branches, en la configuracion no aparece el "status check" para que ejecute travis-ci en cada pull request, asique algo debe estar faltando

**Comment by fdemian** [comment]
Si, fijate esto Gonza, la cuenta de Travis me lo pasa como migrado. 

![Captura](https://user-images.githubusercontent.com/1574757/57426524-e25a3680-71f5-11e9-9f8b-eb4e7eed9a74.JPG)

Capaz hay que darle tiempo... o editar eso a mano.

**Comment by gndelia** [comment]
Sisi, está migrado eso. Debe faltar revisar algo de la configuracion.

**Comment by gndelia** [comment]
Generé un nuevo pull request (ver #38 ) y ahi si me generó un job

https://github.com/UTNianos/frontend/pull/38/checks?check_run_id=123783820

Lo malo es que para el PR existente no me genera ya un build; igual si mergeas ese, mergeo desde master el otro y al pushear ahi ya deberia correrlo. Asique creo que salimos andando

**Comment by fdemian** [comment]
Ahi hice merge del cambio de dominio.  Falta hacer merge del otro. Queres generar un nuevo PR o lo mergo como esta?

**Comment by gndelia** [comment]
Ahi me corrió los checks para el PR #36 

![image](https://user-images.githubusercontent.com/352474/57551658-fad66800-733f-11e9-8d87-2cfaddfaedb4.png)


doy este ticket por cerrado
