### ISSUE TITLE
React-Router-Redux

### ISSUE THREAD

**Issue by fdemian** [UTNianos/frontend#7]
Aparentemente usar React-Router rompe Time Travel en Redux Devtools. 
React Router Redux, sincroniza history con store ( ver el [Repositorio de React-Router-Redux](https://github.com/reactjs/react-router-redux) ).

**Comment by fdemian** [comment]
@Javier-Rotelli  le podés hechar un vistazo a eso?

**Comment by Javier-Rotelli** [comment]
el tema es que react router redux estaba super verde y se rompia bastante, react router anda dentro de todo, y romper time travel cuando cambias de ruta no es tan terrible, en lineas generales lo usas para la navegacion dentro de una misma pagina

**Comment by fdemian** [comment]
¿Que tan roto estaba y hace cuanto lo miraste? 

De todas formas, no me quema mucho tener esto, de hecho seguramente es mejor dejar de complicar el repo con más librerías. 

Esta semana tampoco voy a tener mucho tiempo de ver las cosas, asi que lo cierro y cualquier cosa si a alguien le hace ruido al usar las devtools lo reabrimos.

**Comment by Javier-Rotelli** [comment]
👍 lo vamos viendo, estaba roto roto, no andaba como decia la documentacion, y las rutas se jodian
