### ISSUE TITLE
Integrar Redux-Devtools

### ISSUE THREAD

**Issue by fdemian** [UTNianos/frontend#8]
Integrar Redux-Devtools particularmente time-travel.

**Comment by Javier-Rotelli** [comment]
ya estaban integradas ;)

**Comment by fdemian** [comment]
:open_mouth: 

Como las corro? :P

**Comment by Javier-Rotelli** [comment]
https://github.com/zalmoxisus/redux-devtools-extension

**Comment by fdemian** [comment]
Ok, funcionan. Habría que agregarlo a las notas. :P Fijate si podés ver #7 despues (parece que react-router rompe time travel).
